//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities5 : DbContext
    {
        public DBEntities5()
            : base("name=DBEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicInfo> AcademicInfos { get; set; }
        public virtual DbSet<Apply> Applies { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<UsersDetail> UsersDetails { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
    }
}
