//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersDetail()
        {
            this.AcademicInfos = new HashSet<AcademicInfo>();
            this.Applies = new HashSet<Apply>();
        }
    
        public int Nid { get; set; }
        public string Name { get; set; }
        public string FathersName { get; set; }
        public string MotherName { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string Religion { get; set; }
        public string Age { get; set; }
        public string Status { get; set; }
        public Nullable<int> Uid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicInfo> AcademicInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apply> Applies { get; set; }
        public virtual Login Login { get; set; }
    }
}
